### ISSUE TITLE
Kontakt Beacon count zero

### ISSUE THREAD

**Issue by Leezaa** [kontaktio/kontakt-ios-sdk-workshop#1]
I am new to swift. I followed the kontakt document for ios SDK QuickStart. The project is running but no beacons are detected.  I have uploaded a screenshot. Kindly let me know if I am doing something wrong. I cannot figure out why.

**Comment by stoprocent** [comment]
Hi

Sorry for removing your screenshot, but your API key was visible there.
I have checked your account and your devices are set to Eddystone advertising :)

You have to either use `KTKEddystoneManager` or change the profile to bacon through Kontakt. I Administration App

**Comment by Leezaa** [comment]
Thank you. It worked :)
